version: '3.8'

services:
  db:
    container_name: champion_db
    build:
      context: ./infra/db
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 60s
      retries: 5
      start_period: 4s
    networks:
      champion_network:
        ipv4_address: 172.28.1.3
    ports:
       - ${DB_PORT}:5432
  backend:
    container_name: champion_backend
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./champion-backend
    networks:
      champion_network:
        ipv4_address: 172.28.1.2
  frontend:
    tty: true
    container_name: champion_frontend
    build:
      target: dev
      context: ./champion-frontend
    ports:
      - "8080:8080"
    networks:
      champion_network:
        ipv4_address: 172.28.1.1

networks:
  champion_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16