version: '3.8'

services:
  db:
    tty: true
    container_name: champion-db
    build:
      context: ./infra/db
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 2s
      timeout: 60s
      retries: 5
      start_period: 4s
    networks:
      champion_network:
        ipv4_address: 172.28.1.4
    ports:
       - ${DB_PORT:-5432}:5432
  server:
    image: nginx:latest
    tty: true
    container_name: champion-server
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    ports:
      - "8888:80"
      - "4444:443"
    volumes:
      - server_logs:/var/log/nginx
      - frontend_dist:/var/www/champion/dist
      - ./champion-backend/:/var/www/champion:delegated
#      - ./infra/server/cert/selfsigned.crt:/etc/ssl/certs/selfsigned.crt
#      - ./infra/server/cert/selfsigned.key:/etc/ssl/private/selfsigned.key
      - ./infra/server/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      champion_network:
        ipv4_address: 172.28.1.3
  backend:
    tty: true
    container_name: champion-backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./champion-backend:/var/www/champion:delegated
      - ./infra/php/php.ini:/usr/local/etc/php/php.ini:ro
    build:
      context: ./champion-backend
    networks:
      champion_network:
        ipv4_address: 172.28.1.2
  frontend:
    tty: true
    container_name: champion-frontend
    build:
      target: dev
      context: ./champion-frontend
    volumes:
      - ./champion-frontend/src:/var/www/champion/src
    ports:
      - "8080:8080"
    networks:
      champion_network:
        ipv4_address: 172.28.1.1

networks:
  champion_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  server_logs:
  frontend_dist:
